### ISSUE TITLE
Any thoughts on using DB backed scheduler with celery beat and tenant schemas?

### ISSUE THREAD

**Issue by rajeshyogeshwar** [maciej-gol/tenant-schemas-celery#19]
Hello, do you have any thoughts as to how one can proceed with having a DB backed scheduler? The point is I might stumble upon a requirement where I have to do this. Also, per tenant there is an added complexity of time zones as every tenant might have entities that follow different time zones and then the tasks are be as per that timezone.

**Comment by maciej-gol** [comment]
Thanks for asking! I'll look into this in the evening CEST and will see how this can be solved painlessly :D

**Comment by Rajesh-Yogeshwar** [comment]
I will be looking to help and contribute as well if the need be.

**Comment by maciej-gol** [comment]
Have you checked [crontab](http://docs.celeryproject.org/en/latest/reference/celery.schedules.html#celery.schedules.crontab)? Let's say you have a periodic task `foo` that should be ran at 12pm for every client. You could do something along these lines:

```python
# Run the task every hour.
@periodic_task(crontab(minute='0'))
def run_foo():
    for tenant in get_all_tenants():
        # Make sure connection's tenant is set correctly.
        with connection.set_tenant(tenant):
            run_time = TaskRunTimes.objects.get(task_name='foo')  # Get run time for the tenant.
            schedule = crontab(minute='0', hour='12', nowfun=lambda: datetime.now(pytz.timezone(tenant.timezone))
            if not schedule.is_due(run_time.last_run_at):
                continue

            run_time.last_run_at = datetime.now()
            run_time.save()
            foo.delay()
```

Basically, what it does is that for each tenant it stores the last run time of the task in the database. Combined with tenant's timezone, you can check if the task should be ran or not. The downside is that it always runs the check for all the tenants.

Alternatively, you can iterate over a list of timezones, and do the check earlier so that it does not loop over tenants that should not be run.

```python
# Run the task every hour.
@periodic_task(crontab(minute='0'))
def run_foo():
    for timezone_name in get_tenants_timezones():
        run_time = TaskRunTimes.objects.get(task_name='foo', timezone=timezone_name)  # Get run time for the timezone.
        schedule = crontab(minute='0', hour='12', nowfun=lambda: datetime.now(pytz.timezone(timezone_name))
        if not schedule.is_due(run_time.last_run_at):
            continue

        run_time.last_run_at = datetime.now()
        run_time.save()
        for tenant in get_tenants(timezone=timezone_name):
            # Make sure connection's tenant is set correctly.
            with connection.set_tenant(tenant):
                foo.delay()
```

The benefit of the second solution is that you don't iterate over all the tenants to check if the task should be ran, but only for tenants from timezones you are sure it should run.
