### ISSUE TITLE
Test against python 3.7, 3.8

### ISSUE THREAD

**Issue by thenewguy** [maciej-gol/tenant-schemas-celery#36]
Looks like python newer than 3.6 is missing from tests on travis

**Comment by maciej-gol** [comment]
Hey!

Yes, at the time I was updating the CI config (~January), py3.7 and py3.8
were missing from Travis CI trusty config. And I couldn't migrate to
xenial, because of rabbitmq service issues :-(

wt., 28 kwi 2020 o 23:27 thenewguy <notifications@github.com> napisał(a):

**Comment by thenewguy** [comment]
No worries. Just found the project and it looks awesome 👍 I would have submitted a pr for the minor change but am not familiar with Travis config

**Comment by tomturner** [comment]
@maciej-gol You might find it better to swap to the Github workflows instead of Travis CI. I have done this for django-tenants

**Comment by maciej-gol** [comment]
Changed test running to use docker so that I can finally run them like a man, not like animal. As a side effect, the matrix includes python 3.6-3.8 (like an animal).

@tomturner thanks for the tip! Haven't looked into workflows yet, but I'm looking into automated publishing. I'm doing it so rarely I always forget how to do it before next release.
