### ISSUE TITLE
How to know the tenant of each active or scheduled task

### ISSUE THREAD

**Issue by fproldan** [maciej-gol/tenant-schemas-celery#54]
Hi, I wanted to know if there is any way to get or add the `schema_name` in the tasks when using inspect with active or scheduled tasks.

That is, when doing `app.control.inspect().active()` or `app.control.inspect().scheduled()` to be able to know the `schema_name` of each task.

Right now I get for example:

```python
{
  'eta': '2022-05-10T14:59:00-03:00',
  'priority': 6,
  'request': {
    'id': '305fbf5f-9dd0-4fbf-a698-31afd5f259f8',
    'name': 'my_app.tasks.my_task',
    'args': ['foo', 'bar'],
    'kwargs': {},
    'type': 'my_app.tasks.my_task',
    'hostname': 'celery@francisco',
    'time_start': None,
    'acknowledged': False,
    'delivery_info': {
      'exchange': '',
      'routing_key': 'celery',
      'priority': 0,
      'redelivered': None
    },
    'worker_pid': None
  }
}
```

I need to know which tenant it belongs to

Thanks!

**Comment by maciej-gol** [comment]
Heya!

Since Celery 4.0, this package using the task's headers to transfer the name of the schema to use (the `headers` argument to `.apply_async()`). I'm afraid celery doesn't currently allow you dumping what the headers are :(

You would need to subclass the default Celery Worker class to extend it's functionality and add the headers to the output.

Any reason you want to know the schema name? Maybe it can be known from a different source.

**Comment by fproldan** [comment]
Hello, thank you for your reply!

Due to business logic, I need to know to which tenant belongs the tasks that are running or scheduled in the worker.
I close the issue as it seems it is not a problem with this app.

Thank you!
