### ISSUE TITLE
Create a changelog

### ISSUE THREAD

**Issue by adnathanail** [maciej-gol/tenant-schemas-celery#85]
Thanks for this package it's very handy!

Would it be possible for you to create a changelog so I can more easily review new updates?

Cheers!

**Comment by maciej-gol** [comment]
Yes, I will look into this! Glad to see the package is helpful 😁

pon., 7 sie 2023, 14:31 użytkownik Alex Nathanail ***@***.***>
napisał:

**Comment by tartieret** [comment]
@maciej-go I agree this is a great package, thanks for your work ! Is there any way to check what was in the latest 2.2.0 ?

**Comment by maciej-gol** [comment]
@adnathanail added tag-based releases to GitHub!

@tartieret you can see the changes included in 2.2.0 here: https://github.com/maciej-gol/tenant-schemas-celery/releases/tag/2.2.0. Notably, only the `Fix potential deadlock during migrations caused by Celery Beat by @edg956 in https://github.com/maciej-gol/tenant-schemas-celery/pull/75` change is meaningful to the library.

**Comment by tartieret** [comment]
Great thanks!

**Comment by adnathanail** [comment]
Thanks very much!
